# Site Settings
baseurl: 		""
title: 			free-flow

name: 			free-flow
description: 	freedom through flow activities
url: 			"http://free-flow.gr"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			ioannisaliazis@mac.com

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2016 free-flow.gr	

# Build Settings
permalinks: 	pretty